development:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  username:
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: quiz_dot_ai
  username: root
  password: root
  host: localhost